name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4  # Updated version to support Node.js 20

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated version for Node.js 20
      with:
        python-version: '3.12.0'  # Specify your Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Streamlit app
    - name: Run Streamlit
      run: |
        streamlit run app.py --server.port $PORT
      env:
        PORT: 8501  # Default port for Streamlit, change as needed
