name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions default OS, works for the deployment pipeline

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'  # Reflects your local Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit
      run: |
        streamlit run app.py --server.port $PORT
      env:
        PORT: 8501  # Port for Streamlit app
